
import { useMemo, useState } from 'react';
import type { Question } from '../types/Question';
import type { QuestionAnnotation } from '../types/QuestionAnnotation';
import { updateQuestionAnnotation } from '../services/questionAnnotationStorage';
type Props={questions:Question[];annotations:QuestionAnnotation[];onChange:(items:QuestionAnnotation[])=>void;onStart:(questions:Question[])=>void;onBack:()=>void};
export default function FavoritesMemoPage({questions,annotations,onChange,onStart,onBack}:Props){
 const [filter,setFilter]=useState<'ALL'|'FAVORITE'|'MEMO'>('ALL'); const [search,setSearch]=useState('');
 const visible=useMemo(()=>questions.filter((q)=>{const a=annotations.find((i)=>i.questionId===q.id);const matchFilter=filter==='ALL'||(filter==='FAVORITE'&&a?.favorite)||(filter==='MEMO'&&Boolean(a?.memo.trim()));const keyword=search.trim().toLowerCase();return matchFilter&&(!keyword||q.text.toLowerCase().includes(keyword)||q.category.toLowerCase().includes(keyword));}),[questions,annotations,filter,search]);
 const favorites=questions.filter((q)=>annotations.find((i)=>i.questionId===q.id)?.favorite);
 const update=(id:string,value:Partial<Pick<QuestionAnnotation,'favorite'|'memo'>>)=>onChange(updateQuestionAnnotation(annotations,id,value));
 return <main className="app-shell"><section className="home-card annotations-card"><p className="eyebrow">FAVORITES & MEMOS</p><h1>お気に入り・メモ</h1><div className="annotation-toolbar"><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="問題文・カテゴリを検索"/><select value={filter} onChange={(e)=>setFilter(e.target.value as typeof filter)}><option value="ALL">すべて</option><option value="FAVORITE">お気に入り</option><option value="MEMO">メモあり</option></select></div><button className="weak-button" type="button" disabled={favorites.length===0} onClick={()=>onStart(favorites)}>お気に入りだけ復習（{favorites.length}問）</button><div className="annotation-list">{visible.map((q)=>{const a=annotations.find((i)=>i.questionId===q.id);return <article key={q.id} className={a?.favorite?'annotation-item is-favorite':'annotation-item'}><div className="annotation-heading"><div><span>{q.category}</span><strong>{q.text}</strong></div><button type="button" onClick={()=>update(q.id,{favorite:!a?.favorite})}>{a?.favorite?'★ お気に入り':'☆ お気に入り追加'}</button></div><textarea rows={3} value={a?.memo??''} onChange={(e)=>update(q.id,{memo:e.target.value})} placeholder="この問題についてのメモ"/></article>;})}{visible.length===0&&<div className="empty-state">該当する問題がありません。</div>}</div><button className="secondary-button" type="button" onClick={onBack}>前のメニューへ戻る</button></section></main>;
}
