import { useMemo, useState } from 'react';
import type { Question } from '../types/Question';
import type { QuestionState } from '../types/QuestionState';
import { getMasteryLabel } from '../services/questionStateService';
type Props={questions:Question[];questionStates:QuestionState[];onChange:(items:Question[])=>void;onImport:()=>void;onBack:()=>void;};
const emptyQuestion=():Question=>({id:'',category:'',text:'',choices:['','','',''],answerIndex:0,explanation:'',weight:1,difficulty:1});
export default function QuestionManagementPage({questions,questionStates,onChange,onImport,onBack}:Props){
 const [search,setSearch]=useState('');const [category,setCategory]=useState('ALL');const [editing,setEditing]=useState<Question|null>(null);const [originalId,setOriginalId]=useState('');const [error,setError]=useState('');
 const categories=useMemo(()=>['ALL',...new Set(questions.map(q=>q.category))],[questions]);
 const filtered=useMemo(()=>questions.filter(q=>(category==='ALL'||q.category===category)&&(!search.trim()||`${q.id} ${q.text} ${q.category} ${q.explanation}`.toLowerCase().includes(search.trim().toLowerCase()))),[questions,search,category]);
 const startNew=()=>{setOriginalId('');setEditing(emptyQuestion());setError('');};const startEdit=(q:Question)=>{setOriginalId(q.id);setEditing({...q,choices:[...q.choices]});setError('');};
 const save=()=>{if(!editing)return;const id=editing.id.trim();if(!id||!editing.category.trim()||!editing.text.trim()){setError('問題ID、カテゴリ、問題文は必須です。');return;}if(editing.choices.length<2||editing.choices.some(c=>!c.trim())){setError('選択肢は2件以上、すべて入力してください。');return;}if(questions.some(q=>q.id===id&&q.id!==originalId)){setError('同じ問題IDが既に存在します。');return;}if(editing.answerIndex<0||editing.answerIndex>=editing.choices.length){setError('正解の選択肢を指定してください。');return;}const next={...editing,id,category:editing.category.trim(),text:editing.text.trim(),choices:editing.choices.map(c=>c.trim()),explanation:editing.explanation.trim()};onChange(originalId?questions.map(q=>q.id===originalId?next:q):[...questions,next]);setEditing(null);};
 const remove=(id:string)=>{if(!window.confirm(`問題 ${id} を削除しますか？`))return;onChange(questions.filter(q=>q.id!==id));};
 if(editing)return <main className="app-shell"><section className="home-card question-admin-card"><p className="eyebrow">QUESTION EDIT</p><h1>{originalId?'問題編集':'問題登録'}</h1><div className="form-grid"><label className="form-item"><span>問題ID</span><input value={editing.id} onChange={e=>setEditing({...editing,id:e.target.value})}/></label><label className="form-item"><span>カテゴリ</span><input value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}/></label><label className="form-item"><span>問題文</span><textarea value={editing.text} onChange={e=>setEditing({...editing,text:e.target.value})}/></label>{editing.choices.map((choice,index)=><label className="form-item" key={index}><span>選択肢 {index+1}{editing.answerIndex===index?'（正解）':''}</span><div className="choice-edit-row"><input value={choice} onChange={e=>{const choices=[...editing.choices];choices[index]=e.target.value;setEditing({...editing,choices});}}/><button type="button" onClick={()=>setEditing({...editing,answerIndex:index})}>正解にする</button></div></label>)}<label className="form-item"><span>解説</span><textarea value={editing.explanation} onChange={e=>setEditing({...editing,explanation:e.target.value})}/></label><label className="form-item"><span>出題ウェイト</span><input type="number" min="0.1" step="0.1" value={editing.weight} onChange={e=>setEditing({...editing,weight:Number(e.target.value)})}/></label><label className="form-item"><span>難易度</span><input type="number" min="1" max="5" value={editing.difficulty} onChange={e=>setEditing({...editing,difficulty:Number(e.target.value)})}/></label></div>{error&&<div className="error-box">{error}</div>}<button className="primary-button" onClick={save}>保存</button><button className="secondary-button" onClick={()=>setEditing(null)}>キャンセル</button></section></main>;
 return <main className="app-shell"><section className="home-card question-admin-card"><p className="eyebrow">QUESTION MANAGEMENT</p><h1>問題管理</h1><div className="question-toolbar"><input placeholder="問題文・ID・解説を検索" value={search} onChange={e=>setSearch(e.target.value)}/><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></div><div className="question-count">{filtered.length} / {questions.length}件</div><div className="question-list">{filtered.map(q=><article key={q.id} className="question-item"><div><span>{q.category}</span><strong>{q.text}</strong><small>{q.id}・ウェイト {q.weight}・難易度 {q.difficulty}・{getMasteryLabel(questionStates.find(state=>state.questionId===q.id)?.masteryLevel??'UNLEARNED')}</small></div><div className="question-actions"><button onClick={()=>startEdit(q)}>編集</button><button className="delete-button" onClick={()=>remove(q.id)}>削除</button></div></article>)}</div><button className="primary-button" onClick={startNew}>新しい問題を登録</button><button className="secondary-button" onClick={onImport}>CSVから一括登録</button><button className="secondary-button" onClick={onBack}>ホームへ戻る</button></section></main>;
}
